### PR TITLE
Move to DifferenceEquations.jl

### PR DESCRIPTION
**Pull request by cpfiffer**
This PR is a bit of a weird one since using it (currently) requires pulling in two dev branches:

- [cpfiffer/DifferenceEquations.jl](https://github.com/cpfiffer/DifferenceEquations.jl/tree/csp/nonlinear), using the `csp/nonlinear` branch.
- [The PR](https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/pull/84) in DSSM, intended to move us to 0.4.4. We can also just merge this over so that the only dev branch we need is DifferenceEquations.jl.

## What's different: The joint solver and `ConditionalGaussian`

The primary difference in this PR is how the Kalman or arbitrary functional solvers are called inside `turing_models.jl`. We used to have a slightly more parsimonious form for the joint solver (referred to as `ConditionalGaussian` in DifferenceEquations)

```julia
Turing.@addlogprob! solve(sol, x0, (0, T); noise = ϵ, observables = z).logpdf
```

but now it is

```julia
    # Simulate and get the likelihood.
    problem = StateSpaceProblem(
        DifferentiableStateSpaceModels.dssm_evolution,
        DifferentiableStateSpaceModels.dssm_volatility,
        DifferentiableStateSpaceModels.dssm_observation,
        x0,
        (0,T),
        sol,
        noise=DefinedNoise(ϵ),
        obs_noise=sol.D,
        observables = z
    )

    simulation = solve(
        problem, 
        ConditionalGaussian(); 
        vectype=Zygote.Buffer
    )

    Turing.@addlogprob! simulation.likelihood
```

This can go away later -- i.e. we can relatively easily define a convenience function `StateSpaceProblem(sol, x0, T, epsilon, z)` that will eliminate the bulk of the first function call.

## What's different: The Kalman solver and `KalmanFilter`

To use the Kalman filter, the lines are

```julia
    # Simulate and get the likelihood.
    T = length(z)
    problem = LinearStateSpaceProblem(
        sol.A,
        sol.B,
        sol.C,
        sol.x_ergodic,
        (0,T),
        noise=sol.Q,
        obs_noise=sol.D,
        observables = z
    )

    simulation = solve(
        problem, 
        KalmanFilter(); 
        vectype=Zygote.Buffer
    )

    Turing.@addlogprob! simulation.likelihood
```

## Doing an end run around Zygote and avoiding type piracy

Since DifferenceEquations.jl cannot depend on zygote directly, I wrote a bit of code to arbitrarily wrap the vectors containing `u` (the latent spaces), `z` (the observations), `P` (prior variances if using the Kalman filter), and `n` (the latent noise) in a Zygote.Buffer. That's why in the `solve` code we're using this weird `vectype` keyword argument when calling `solve`:

```julia
    simulation = solve(
        problem, 
        KalmanFilter(); 
        vectype=Zygote.Buffer
    )
```
Everything seems to be running, at least locally.

### CODE REVIEW

**Comment by cpfiffer** [comment]
I merged in the type stability code from #30

**Comment by wupeifan** [comment]
We probably need to remove the `path` in the manifest file. But later.

**Comment by wupeifan** [comment]
Why there are changes in the generated FVGQ models?

**Comment by cpfiffer** [comment]
Huh, that's a good question. It looks to me like just an ordering issue? Not sure what would cause that.

**Comment by wupeifan** [comment]
I might override some of these changes if you don't mind @cpfiffer . Just as a practice, let me test some of these and then tell you what I get.

**Comment by cpfiffer** [comment]
Go for it!

**Comment by wupeifan** [comment]
I think it's almost there, but there are a couple of things I need to check in DifferenceEquations.jl before we make a bit more edits or merge.

**Comment by wupeifan** [comment]
This is working at least for RBC models, (with all the issues we known), so I'll merge this.

**Pull request merged**
